name: deploying all lambdas

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_match:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lambda-function:
          - function-path: create_match
            function-name: CreateMatch
          - function-path: delete_match
            function-name: DeleteMatch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ secrets.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          cd ${{ matrix.lambda-function.function-path }}
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
          cd ..

      - name: Zip Lambda Function
        run: |
          cd ${{ matrix.lambda-function.function-path }}
          zip -r lambda_function.zip .
          cd ..

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws lambda update-function-code --function-name ${{  matrix.lambda-function.function-name }} --zip-file fileb://${{  matrix.lambda-function.function-path }}.zip